version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    command: "-b /opt/irisapp/hostname.sh"
    init: true
    restart: always
    ports: 
      - 49158:1972
      - 32792:52773
      - 53773
    volumes:
      - ./:/irisdev/app
      - /tmp:/shared
